//SPDX-License-Identifier: AGPL-3.0-or-later
pragma solidity ^0.8.19;

//============= Enums ==============
enum Role {
    ORGANIZATION,
    PARTICIPANT
}

enum TicketType {
    REGULAR,
    VIP,
    VVIP
}

/*
*@dev Categories of events
*/

enum Categories {
    CONFERENCES,
    SEMINARS,
    WORKSHOPS,
    NETWORKING,
    TRADE_SHOWS,
    MIXERS,
    MEETUPS,
    SOCIAL_GATHERING,
    PARTIES,
    LECTURES,
    CLASSES,
    WEBMINARS,
    CONCERTS,
    FESTIVALS,
    PERFORMANCES,
    MOVIE_SCREENINGS,
    ARTS_EXHIBITIONS,
    MUSEUM,
    CULTURAL_FESTIVAL,
    HERITAGE_TOURS,
    SPORTS_AND_FITNESS,
    SPORTING,
    TOURNAMENTS,
    FITNESS_CLASSES,
    MARATHONS,
    CHARITY_GALAS,
    FUNDRAISING_DINNER,
    CHARITY_RUNS,
    AUCTIONS,
    WORSHIP_SERVICE,
    SPIRITUAL_RETREATS,
    RELIGIOUS_FESTIVAL,
    MEDITATION_SESSIONS,
    HACKATHONS,
    PRODUCT_LAUCHES,
    TECH_CONFERENCES,
    INNOVATION_FORUMS,
    WEDDINGS,
    ANNIVERSARIES,
    BIRTHDAY_PARTIES,
    GRAUDUATION_PARTIES,
    WELLNESS_RETREATS,
    HEALTH_EXPOS,
    YOGA_RETREATS,
    NUTRITION_WORKSHOP,
    TRAVEL_EXPOS,
    ADVENTURE_TOURS,
    OUTDOORS_EVENTS,
    TRAVEL_MEETUPS,
    FASHION_SHOWS,
    BEAUTY_EXPOS,
    POP_UP_SHOPS,
    FASHION_NETWORKING,
    SCIENCE_FAIRS,
    TECHNOLOGY_EXPOS,
    RESEARCH_SYMPOSIUMS,
    SCIENCE_LECTURES,
    ECO_FRIENDLY_EVENTS,
    SUSTAINABILITY_CONFERENCES,
    ENVIRONMENTAL_WORKSHOPS,
    CONSERVATION_EVENTS,
    OTHERS
}

